// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhtEmf01upWiywSY0ucMaMLG95YCrqY8',
    appId: '1:864815853272:web:c2074bcfeaa8c2c872b1ad',
    messagingSenderId: '864815853272',
    projectId: 'hytch-ride',
    authDomain: 'hytch-ride.firebaseapp.com',
    storageBucket: 'hytch-ride.appspot.com',
    measurementId: 'G-CPFMG173KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZ7JFkgfKUDiVpXJx8e081isc7MIKM3s',
    appId: '1:864815853272:android:05e02340280b431472b1ad',
    messagingSenderId: '864815853272',
    projectId: 'hytch-ride',
    storageBucket: 'hytch-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4IH81-BeoZFkKz19FTqWGjtt88JJPHo4',
    appId: '1:864815853272:ios:074842bb1efc28f072b1ad',
    messagingSenderId: '864815853272',
    projectId: 'hytch-ride',
    storageBucket: 'hytch-ride.appspot.com',
    iosClientId: '864815853272-30n2v60muhq7vhfkrq5u2dd8aqketa12.apps.googleusercontent.com',
    iosBundleId: 'com.hytch.hytch',
  );
}
